version: 2

jobs:
  build:
    docker:
      - image: circleci/python:3.7.5-stretch
        environment:
          DATABASE_URL: postgres://circleci:@127.0.0.1:5432/elections_test
          REDIS_URL: redis://127.0.0.1:6379/0
      - image: circleci/postgres:11-alpine-ram
        environment:
          - POSTGRES_USER=circleci
          - POSTGRES_DB=elections_test
      - image: redis

    steps:
      - checkout

      - run:
          name: Checking system dependencies
          command: make doctor

      - type: cache-restore
        key: poetry-{{ checksum "poetry.lock" }}

      - run:
          name: Installing project dependencies
          command: make install

      - type: cache-save
        key: poetry-{{ checksum "poetry.lock" }}
        paths:
          - .venv

      - run:
          name: Running linters
          command: make check

      - run:
          name: Running tests
          command: make test && sudo pip install coveralls "coverage<5" && coveralls

      - store_artifacts:
          path: htmlcov
