# Generated by Django 2.0.7 on 2018-07-10 22:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='poll',
            unique_together={('county', 'jurisdiction', 'ward', 'precinct')},
        ),
    ]
