# Generated by Django 2.0.6 on 2018-07-02 01:31

import django.utils.timezone
from django.db import migrations

import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [("elections", "0001_initial")]

    operations = [
        migrations.RemoveField(
            model_name="registrationstatus", name="districts"
        ),
        migrations.AddField(
            model_name="district",
            name="created",
            field=model_utils.fields.AutoCreatedField(
                default=django.utils.timezone.now,
                editable=False,
                verbose_name="created",
            ),
        ),
        migrations.AddField(
            model_name="district",
            name="modified",
            field=model_utils.fields.AutoLastModifiedField(
                default=django.utils.timezone.now,
                editable=False,
                verbose_name="modified",
            ),
        ),
        migrations.AddField(
            model_name="districtcategory",
            name="created",
            field=model_utils.fields.AutoCreatedField(
                default=django.utils.timezone.now,
                editable=False,
                verbose_name="created",
            ),
        ),
        migrations.AddField(
            model_name="districtcategory",
            name="modified",
            field=model_utils.fields.AutoLastModifiedField(
                default=django.utils.timezone.now,
                editable=False,
                verbose_name="modified",
            ),
        ),
    ]
