# Generated by Django 2.0.7 on 2018-07-11 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [('elections', '0002_auto_20180710_1841')]

    operations = [
        migrations.AlterModelOptions(
            name='ballot', options={'ordering': ['election__date']}
        ),
        migrations.AlterModelOptions(name='election', options={'ordering': ['date']}),
    ]
