# Generated by Django 2.0.7 on 2018-07-05 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [('elections', '0004_district_population')]

    operations = [
        migrations.AddField(
            model_name='ballot',
            name='mi_sos_html',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='district',
            name='mi_sos_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='election',
            name='mi_sos_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ballot',
            name='mi_sos_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
