# Generated by Django 2.0.7 on 2018-07-05 01:41

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models

import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [('elections', '0005_auto_20180704_2115')]

    operations = [
        migrations.CreateModel(
            name='Precinct',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'created',
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name='created',
                    ),
                ),
                (
                    'modified',
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name='modified',
                    ),
                ),
                ('ward_number', models.PositiveIntegerField()),
                ('number', models.PositiveIntegerField()),
                (
                    'mi_sos_id',
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    'county',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='counties',
                        to='elections.District',
                    ),
                ),
                (
                    'jurisdiction',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='jurisdictions',
                        to='elections.District',
                    ),
                ),
            ],
            options={'abstract': False},
        ),
        migrations.RemoveField(model_name='ballot', name='county'),
        migrations.RemoveField(model_name='ballot', name='jurisdiction'),
        migrations.RemoveField(model_name='ballot', name='mi_sos_url'),
        migrations.RemoveField(model_name='ballot', name='ward'),
        migrations.AlterField(
            model_name='ballot',
            name='precinct',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to='elections.Precinct',
            ),
        ),
    ]
