# Generated by Django 2.0.7 on 2018-07-05 01:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [('elections', '0006_auto_20180704_2141')]

    operations = [
        migrations.RemoveField(model_name='district', name='mi_sos_id')
    ]
