# Generated by Django 2.0.7 on 2018-07-05 01:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [('elections', '0007_remove_district_mi_sos_id')]

    operations = [
        migrations.RenameField(
            model_name='precinct',
            old_name='number',
            new_name='precinct_number',
        )
    ]
