# Generated by Django 2.0.7 on 2018-07-13 02:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("elections", "0007_auto_20180712_2221")]

    operations = [
        migrations.RenameModel(old_name="BallotWebpage", new_name="BallotWebsite")
    ]
