# Generated by Django 2.0.7 on 2018-07-05 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [('elections', '0008_auto_20180704_2143')]

    operations = [
        migrations.AlterUniqueTogether(
            name='precinct',
            unique_together={
                ('county', 'jurisdiction', 'ward_number', 'precinct_number')
            },
        )
    ]
