# Generated by Django 2.0.7 on 2018-07-13 03:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("elections", "0008_auto_20180712_2237")]

    operations = [
        migrations.AddField(
            model_name="ballotwebsite",
            name="source",
            field=models.BooleanField(default=True),
        )
    ]
