# Generated by Django 2.0.7 on 2018-07-05 21:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [('elections', '0009_auto_20180705_0751')]

    operations = [
        migrations.RenameModel(old_name='Precinct', new_name='Poll'),
        migrations.RenameField(
            model_name='ballot', old_name='precinct', new_name='poll'
        ),
        migrations.AddField(
            model_name='position',
            name='poll',
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to='elections.Poll',
            ),
        ),
        migrations.AddField(
            model_name='proposal',
            name='poll',
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to='elections.Poll',
            ),
        ),
    ]
