# Generated by Django 2.0.7 on 2018-07-14 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [('elections', '0012_auto_20180713_1730')]

    operations = [
        migrations.AlterUniqueTogether(
            name='precinct',
            unique_together={('county', 'jurisdiction', 'ward', 'number')},
        )
    ]
