# Generated by Django 2.0.7 on 2018-07-08 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [('elections', '0012_election_active')]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='ward_number',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        )
    ]
