# Generated by Django 2.0.7 on 2018-07-21 22:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("elections", "0013_auto_20180714_1321")]

    operations = [
        migrations.RemoveField(model_name="position", name="candidates"),
        migrations.AddField(
            model_name="candidate",
            name="position",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="elections.Position",
            ),
        ),
        migrations.AlterField(
            model_name="party",
            name="name",
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name="candidate", unique_together={("position", "name")}
        ),
    ]
