# Generated by Django 2.0.7 on 2018-07-09 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [('elections', '0013_auto_20180708_1412')]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='precinct_letter',
            field=models.CharField(blank=True, max_length=1),
        ),
        migrations.AlterUniqueTogether(
            name='poll',
            unique_together={
                (
                    'county',
                    'jurisdiction',
                    'ward_number',
                    'precinct_number',
                    'precinct_letter',
                )
            },
        ),
    ]
