# Generated by Django 2.0.7 on 2018-08-01 02:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("elections", "0014_auto_20180721_1817")]

    operations = [
        migrations.AlterModelOptions(
            name="party", options={"verbose_name_plural": "Parties"}
        )
    ]
