# Generated by Django 2.0.7 on 2018-07-09 21:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [('elections', '0014_auto_20180708_2102')]

    operations = [
        migrations.AddField(
            model_name='registrationstatus',
            name='poll',
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to='elections.Poll',
            ),
        )
    ]
