# Generated by Django 2.0.7 on 2018-07-10 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0016_auto_20180709_2338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='precinct_letter',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='poll',
            name='precinct_number',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='poll',
            name='ward_number',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterUniqueTogether(
            name='poll',
            unique_together={('county', 'jurisdiction', 'ward', 'precinct_number', 'precinct_letter')},
        ),
    ]
