# Generated by Django 2.0.7 on 2018-07-10 04:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [('elections', '0017_auto_20180710_0005')]

    operations = [
        migrations.RemoveField(model_name='poll', name='precinct_letter'),
        migrations.RemoveField(model_name='poll', name='precinct_number'),
        migrations.RemoveField(model_name='poll', name='ward_number'),
    ]
