# Generated by Django 2.0.8 on 2018-09-30 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [('elections', '0022_auto_20180930_1442')]

    operations = [
        migrations.AddField(
            model_name='ballotwebsite',
            name='fetched',
            field=models.BooleanField(default=False),
        )
    ]
