# Generated by Django 2.0.8 on 2018-10-02 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("elections", "0024_auto_20180930_2030")]

    operations = [
        migrations.AddField(
            model_name="ballotwebsite",
            name="last_parse",
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name="ballotwebsite",
            name="parsed",
            field=models.BooleanField(default=False),
        ),
    ]
