# Generated by Django 2.0.9 on 2018-10-09 22:49

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [("elections", "0028_auto_20181003_0806")]

    operations = [
        migrations.AlterUniqueTogether(
            name="position",
            unique_together={("election", "district", "name", "term", "seats")},
        )
    ]
