# Generated by Django 2.2.6 on 2019-10-22 22:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0033_auto_20191021_2337'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ballotwebsite',
            name='ballot',
        ),
        migrations.AddField(
            model_name='ballot',
            name='website',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='elections.BallotWebsite'),
        ),
        migrations.AddField(
            model_name='ballotwebsite',
            name='ballot_legacy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='elections.Ballot'),
        ),
    ]
