# Generated by Django 2.2.6 on 2019-10-23 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("elections", "0035_auto_20191023_0505")]

    operations = [migrations.RemoveField(model_name="ballotwebsite", name="source")]
