# Generated by Django 2.2.6 on 2019-10-27 00:37

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [("elections", "0037_auto_20191026_1633")]

    operations = [
        migrations.RenameField(
            model_name="ballotwebsite",
            old_name="last_fetch_with_precinct",
            new_name="last_validate",
        )
    ]
