# Generated by Django 2.2.7 on 2019-11-08 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [('elections', '0043_registrationstatus_polling_location')]

    operations = [
        migrations.RemoveField(model_name='ballotwebsite', name='refetch_weight')
    ]
