# Generated by Django 3.0.3 on 2020-02-18 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0046_remove_party_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrationstatus',
            name='recently_moved',
            field=models.BooleanField(default=False),
        ),
    ]
