# Generated by Django 3.0.7 on 2020-06-05 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0048_position_section'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='seats',
            field=models.PositiveIntegerField(blank=True, default=1),
        ),
        migrations.AlterField(
            model_name='position',
            name='term',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
