# Generated by Django 3.0.7 on 2020-06-07 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0049_position_allow_blanks'),
    ]

    operations = [
        migrations.AddField(
            model_name='districtcategory',
            name='rank',
            field=models.IntegerField(
                default=0, help_text='Controls ballot item ordering'
            ),
        ),
    ]
