# Generated by Django 3.0.8 on 2020-08-14 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0050_districtcategory_rank'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrationstatus',
            name='absentee_application_received',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='registrationstatus',
            name='absentee_ballot_received',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='registrationstatus',
            name='absentee_ballot_sent',
            field=models.DateField(null=True),
        ),
    ]
