# Generated by Django 3.1.13 on 2021-10-31 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0058_registrationstatus_ballot'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registrationstatus',
            old_name='dropbox_location',
            new_name='dropbox_locations',
        ),
    ]
