# Generated by Django 3.2.15 on 2022-09-23 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("elections", "0060_ballot_item_described"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="election",
            name="description",
        ),
        migrations.RemoveField(
            model_name="proposal",
            name="described",
        ),
    ]
