# Generated by Django 3.2.18 on 2023-03-14 23:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0064_ballot_items'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ballot',
            name='website',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='elections.ballotwebsite'),
        ),
    ]
