# Generated by Django 5.0b1 on 2024-02-10 02:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("elections", "0065_ballot_website_nonnull"),
    ]

    operations = [
        migrations.AlterField(
            model_name="election",
            name="active",
            field=models.BooleanField(db_index=True, default=True),
        ),
    ]
