# Generated by Django 5.0.9 on 2024-10-12 21:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("elections", "0067_index_various_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="candidate",
            name="nomination",
            field=models.ForeignKey(
                blank=True,
                help_text="Party that nominated the candidate for a nonpartisan position",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="nominations",
                to="elections.party",
            ),
        ),
    ]
