# Generated by Django 5.0.9 on 2024-10-13 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("elections", "0068_candidate_nomination"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="candidate",
            options={"ordering": ["party__name", "nomination__name", "name"]},
        ),
    ]
